# Protocols:
#       NEC=0x01,
#		RC5=0x02,
#		RC6=0x03,
#		RCMM=0x04,
#		KONKA=0x05,
#		HAIER=0x06,
#		RCA=0x07,
#		P7051=0x08,
#		TOSHIBA=0x09
#		RC5X=0x0A,
#		RC6_Mode0=0x0B,
[Kernel]
1=KIR_SCYK-W-005B
2=KIR_Cultraview

[KIR_SCYK-W-005B]0x62
Enable=true #true or false
Protocol=0x01
Header=0x00BF
Keymap=KIR_SCYK-W-005B_Keymap

[KIR_Cultraview]
Enable=true #true or false
Protocol=0x01
Header=0x41FB
Keymap=KIR_Cultraview_Keymap

[KIR_SCYK-W-005B_Keymap]
KEY_POWER               =       0x00
KEY_MUTE                =       0x01
KEY_0                   =       0x0C
KEY_1                   =       0x02
KEY_2                   =       0x03
KEY_3                   =       0x04
KEY_4                   =       0x05
KEY_5                   =       0x06
KEY_6                   =       0x07
KEY_7                   =       0x08
KEY_8                   =       0x09
KEY_9                   =       0x0A
KEY_SETTINGS            =       0x0B
KEY_CHANNEL             =       0x0D       # CHRTN
KEY_SLEEP_MODE          =       0x43       # Sleep
KEY_ZOOM                =       0x44       # ZOOM
KEY_TV_FAVORITE_LIST    =       0x5B       # FAV
KEY_CHANNELDOWN         =       0x4B
KEY_CHANNELUP           =       0x4A
KEY_VOLUMEDOWN          =       0x49
KEY_VOLUMEUP            =       0x48
KEY_PICTURE_MODE        =       0x41       # PictureMode
KEY_SOUND_MODE          =       0x42       # Audio  #SoundMode
KEY_TV_CHANNEL_LIST     =       0x5E       # List
KEY_INFO                =       0x40       # Info
KEY_HOME                =       0x61       # Home
KEY_KP1                 =       0x0F       # Source
KEY_HDMI                =       0x1f

KEY_MENU                =       0x16       # Menu
KEY_BACK                =       0x15       # Exit
KEY_UP                  =       0x13       # up
KEY_DOWN                =       0x14       # down
KEY_LEFT                =       0x11       # left
KEY_RIGHT               =       0x12       # right
KEY_ENTER               =       0x10       # Enter
KEY_RED                 =       0x4c       # RED
KEY_GREEN               =       0x4d       # GREED
KEY_YELLOW              =       0x4e       # YELLOW
KEY_BLUE                =       0x4f
KEY_PLAYPAUSE           =       0x51       # Play_Pause
KEY_REWIND              =       0x56       # <<  //TTX
KEY_FORWARD             =       0x57       # >>
KEY_STOP                =       0x52       # STOP
KEY_PREVIOUSSONG        =       0x54       # |<<
KEY_NEXTSONG            =       0x55       # >>|
KEY_TV                  =       0x83
KEY_MEDIA_GOTO          =       0xCC
KEY_FREEZE_MODE         =       0x81
KEY_MOUSE               =       0x62
KEY_MEDIA1              =       0x60
KEY_APP_CUSTOM1         =       0x58
KEY_HELP                =        0x00      # EPG
KEY_APP_NETFLIX         =       0x73       # NETFLIX
KEY_APP_YOUTUBE         =       0x82       # YOUTUBE



[KIR_Cultraview_Keymap]
KEY_POWER               =       0x82       # Power
KEY_KP1                 =       0x93       # Source

KEY_1                   =       0x88       # 1
KEY_2                   =       0x89       # 2
KEY_3                   =       0x8A       # 3
KEY_4                   =       0x8C       # 4
KEY_5                   =       0x8D       # 5
KEY_6                   =       0x8E       # 6
KEY_7                   =       0x90       # 7
KEY_8                   =       0x91       # 8
KEY_9                   =       0x92       # 9
KEY_0                   =       0x95       # 0
KEY_F1                  =       0x94       # "-/-"

KEY_UP                  =       0x99       # up
KEY_DOWN                =       0x9D       # down
KEY_LEFT                =       0x9C       # left
KEY_RIGHT               =       0x9E       # right
KEY_ENTER               =       0x9A       # Enter

KEY_MUTE                =       0xD0       # MUTE
KEY_INFO                =       0x98       # Info
KEY_MENU                =       0x97       # Menu
KEY_BACK                =       0xCC       # Exit

KEY_CHANNELUP           =       0x9B       # CH+
KEY_CHANNELDOWN         =       0x8F       # CH-
KEY_VOLUMEUP            =       0x9F       # Vol+
KEY_VOLUMEDOWN          =       0x8B       # Vol-

KEY_SLEEP_MODE          =       0xD1       # Sleep
KEY_PICTURE_MODE        =       0xCD       # PictureMode
#KEY_SOUND              =       0xCE       # Sound
KEY_TV_AUDIO_TRACK      =       0xCF       # MTS
KEY_SOUND_MODE          =       0xCE       # Audio  #SoundMode
KEY_ZOOM                =       0xC3       # ZOOM
KEY_FAC_MENU            =       0xD7       # FAV

KEY_RED                 =       0xC8       # RED
KEY_MOUSE               =       0xC9       # GREED
KEY_YELLOW              =       0xCA       # YELLOW
KEY_BLUE                =       0xCB       # BLUE

KEY_CHANNEL             =       0x96       # CHRTN
KEY_TV_CHANNEL_LIST     =       0xd4       # List
KEY_HELP                =       0xD5       # EPG
KEY_TV                  =       0xC2       # DTV_ATV

KEY_REWIND              =       0x80       # <<
KEY_FORWARD             =       0xC0       # >>
KEY_PREVIOUSSONG        =       0xC1       # |<<
KEY_NEXTSONG            =       0xDC       # >>|

KEY_PLAYPAUSE           =       0x81       # Play_Pause
#KEY_PAUSE              =       0x81       # Pause
KEY_STOP                =       0x87       # Stop

#KEY_PAGEUP             =       0x         # Page up
#KEY_PAGEDOWN           =       0x         # Page down

KEY_HOME                =       0xD8       # Home
#KEY_FN_F6              =       0x         # xxx
#KEY_FN_F2              =       0xC4       # Freeze
KEY_TV_SUBTITLE         =       0xD3       # Subtitle
KEY_FN_F4               =       0x84       # TTX
#KEY_FN_F3              =       0x84       # CC
KEY_RECORD              =       0xD2       # Record
#KEY_KP0                =       0x         # PIP
KEY_TV_INDEX            =       0xC7       # Index
#KEY_FN_F5              =       0x         # Mix
KEY_TV_HOLD             =       0xC4       # Hold
KEY_TV_CANCEL           =       0x85       # Update
KEY_TV_REVEAL           =       0x86       # REVEAL
#KEY_VIDEO              =       0xCD       # PictureMode
KEY_TV_SUBPAGE          =       0xC6       # Subcode
KEY_TV_SIZE             =       0xC5       # Size
#KEY_F8                 =       0x83       # Clock
KEY_TV_TIME_SHIFT           =       0x83       # TIME SHIFT
KEY_FAC_RESET               =       0xD9       # RESET
KEY_FAC_BURN                =       0xDa       # AGING

[Mboot]
#define RECOVERY_KEY             KEY_EXIT
#define UPGRADEUSBOTA_KEY        KEY_MENU
#define UPGRADEBOOTLOADER_KEY    KEY_VOLUMEDOWN
#define FORCEUGRADE_KEY          KEY_VOLUMEUP
#define RECOVERYWIPEDATA_KEY     KEY_CHANNELUP
#define RECOVERYWIPECACHE_KEY    KEY_CHANNELDOWN
0=MIR_Mstar
1=MIR_SCYK-W-005B
2=MIR_Cultraview

[MIR_Mstar]
Enable=true
Protocol=0x01
Header=0x807F
RECOVERY_KEY=0x1B
UPGRADEUSBOTA_KEY=0x07
FORCEUGRADE_KEY=0x16
UPGRADEBOOTLOADER_KEY=0x15
RECOVERYWIPEDATA_KEY=0x1F
RECOVERYWIPECACHE_KEY=0x19

[MIR_SCYK-W-005B]
Enable=true
Protocol=0x01
Header=0x00BF
RECOVERY_KEY=0x95
UPGRADEUSBOTA_KEY=0x82
FORCEUGRADE_KEY=0x80
UPGRADEBOOTLOADER_KEY=0x81
RECOVERYWIPEDATA_KEY=0x85
RECOVERYWIPECACHE_KEY=0x86

[MIR_Cultraview]
Enable=true
Protocol=0x01
Header=0x41FB
RECOVERY_KEY=0x88
UPGRADEUSBOTA_KEY=0x89
FORCEUGRADE_KEY=0x8A
UPGRADEBOOTLOADER_KEY=0x8C
RECOVERYWIPEDATA_KEY=0x8D
RECOVERYWIPECACHE_KEY=0x8E

[IR_VERSION]
IrVersion=0x30

[PM51]
0=PIR_IR_Mstar
1=PIR_SCYK-W-005B
2=PIR_NETFLIX_Mstar
3=PIR_IR_Cultraview

[PIR_IR_Mstar]
Enable=true
Protocol=0x01
Header=0x807F
Key0=0x46

[PIR_SCYK-W-005B]
Enable=true
Protocol=0x01
Header=0x00BF
Key0=0x00

[PIR_NETFLIX_Mstar]
Enable=true
Protocol=0x01
Header=0x807F
Key0=0x03

[PIR_IR_Cultraview]
Enable=true
Protocol=0x01
Header=0x41FB
Key0=0x82

[PIR_ADDHOTKEY_GUIDE_Mstar_test]
Enable=true
Protocol=0x01
Header=0x807f
Key0=0x4a

[PIR_ADDHOTKEY_FVP_Mstar_test]
Enable=true
Protocol=0x01
Header=0x807f
Key0=0x5e

[PIR_ADDHOTKEY_LIST_Mstar_test]
Enable=true
Protocol=0x01
Header=0x807f
Key0=0x10

[PIR_ADDHOTKEY_YOUTUBE_Mstar_test]
Enable=true
Protocol=0x01
Header=0x807f
Key0=0x05

[PIR_PRIMEVIDEO]
Enable=true
Protocol=0x01
Header=0x807f
Key0=0x0c

[PM_IR_HOTKEY_SETTING]
WAKE_IRKEY_SCAN_CODE = {0x46,0x03,0x05,0x0c,0x5e,0x10,0x4a,0};
WAKE_IRKEY_KEY_CODE = {0x74,0x68,0x6d,0x3e,0x40,0x18B,0x16D,0};
WAKE_IRKEY_BTN_CODE = {0x0008f000,0x000bf085,0x000bf086,0x000bf089,0x7f004,0x5f003,0x8f002,0};

WAKE_IRKEY_HOTKEY = {0x000bf085,0x000bf086,0x000bf089,0x7f004,0x5f003,0x8f002,0,0};

# KEY_CODE:
# kernel\linux-x.x\include\uapi\linux\input-event-codes.h
# KEY_POWER = 0x74
# KEY_PAGEUP = 0x68
# KEY_PAGEDOWN = 0x6d

# BTN_CODE:
# apollo\middleware\open\extern_if\common\res_mngr\drv\u_btn_map.h
# BTN_POWER = 0x0008f000
# BTN_NETFLIX = 0x000bf085
# BTN_YOUTUBE = 0x000bf086

# The WAKE_IRKEY_HOTKEY must be included by  the WAKE_IRKEY_BTN_CODE

