name: Build TWRP for MT9632
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev pngcrush schedtool squashfs-tools zlib1g-dev libxml2-utils
          sudo wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb && sudo dpkg -i libtinfo5_6.2-0ubuntu2_amd64.deb
          sudo wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.2-0ubuntu2_amd64.deb && sudo dpkg -i libncurses5_6.2-0ubuntu2_amd64.deb

      - name: Sync TWRP Source
        run: |
          mkdir ~/twrp && cd ~/twrp
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo && sudo mv ~/repo /usr/local/bin/repo
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Clone & Patch
        run: |
                - name: Clone & Patch
        run: |
         cd ~/twrp
          mkdir -p device/mediatek/m7332
          git clone https://github.com/salimalqaaod1-lgtm/twrp_device_m7332 device/mediatek/m7332
          cd device/mediatek/m7332
          rm -f vendorsetup.sh
          # هذا السطر سيحذف استدعاء ملفات Omni المفقودة من ملف omni_m7332.mk
          sed -i '/vendor\/omni/d' omni_m7332.mk
          sed -i 's/core_64bit.mk/core_minimal.mk/g' omni_m7332.mk
          sed -i 's|device/m7332|device/mediatek/m7332|g' *.mk || true


      - name: Build
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch omni_m7332-eng
          make recoveryimage -j$(nproc --all)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-m7332-Final
          path: ~/twrp/out/target/product/m7332/recovery.img
